### ISSUE TITLE
More numbers on other sparsities

### ISSUE THREAD

**Issue by GeneZC** [princeton-nlp/CoFiPruning#23]
CoFi is a great work which may benefit the research in related areas.

However, I have found the numbers of the task performance on other sparsities are not available. Could you please provide these numbers in detail?

Besides, metrics besides accuracy scores on GLUE would also be appreciated.

**Comment by xiamengzhou** [comment]
Hi, thanks for checking out our repo! We don't have results for models of a sparsity less than 60% because we rarely observed a performance drop compared to full models. But you can train models with our code for any sparsities you would like to test on!

I currently do not have the bandwidth to get more results/metrics :/ But you can use the script `evaluation.py` to get other metrics with a slight code change.

Let me know if you have more questions!

**Comment by GeneZC** [comment]
Thanks for the reply! I actually expect the numbers on sparsities like 70%, 80%, etc.

**Comment by xiamengzhou** [comment]
Oh! Do you mean the numbers in Figure 2 of the paper? I compiled it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1IF6ReWkSDKnZomvQT9GBlEhfN48NoDyr-XHOvD2vjvs/edit#gid=0). Let me know if you need more data points!

**Comment by GeneZC** [comment]
Many thanks! I would appreciate the results, if available, on other datasets in Table 2 as well.

**Comment by xiamengzhou** [comment]
Hi, unfortunately, we didn't run all the sparsities for all datasets. Let me know if you encounter any problems when producing the results!

**Comment by xiamengzhou** [comment]
Hi, I am closing this issue for now :) Feel free to reopen it if you have more questions.
